### ISSUE TITLE
Nested explanations are unintentionally showing in code panel

### ISSUE THREAD

**Issue by d4vidsha** [d4vidsha/algorithms-in-action.github.io#53]
Nested explanations from pseudocode are unintentionally showing in code panel.
![image](https://github.com/d4vidsha/algorithms-in-action.github.io/assets/70577814/521f9f00-b08b-4d6d-9efe-076ba10e5f75)

**Comment by cate-21** [comment]
The issue was that within the parser, when we are extracting \Expl tags we were expecting a space after the opening brace (i.e., '\Expl { '). This means that \Expl{\nWord..} or even \Expl{Word...} are not recognised. This does appear to be a mistake, as the other tags do not include such a space. I have removed the space from the parser - that \Expl is now hidden, and it does not appear to have interfered with any other explanation.
